-- Migration to enable ON UPDATE CASCADE for profiles foreign keys

-- 1. Drop existing constraints
ALTER TABLE voice_clips DROP CONSTRAINT IF EXISTS voice_clips_user_id_fkey;
ALTER TABLE likes DROP CONSTRAINT IF EXISTS likes_user_id_fkey;
ALTER TABLE comments DROP CONSTRAINT IF EXISTS comments_user_id_fkey;
ALTER TABLE followers DROP CONSTRAINT IF EXISTS followers_follower_id_fkey;
ALTER TABLE followers DROP CONSTRAINT IF EXISTS followers_following_id_fkey;
ALTER TABLE user_badges DROP CONSTRAINT IF EXISTS user_badges_user_id_fkey;
ALTER TABLE validations DROP CONSTRAINT IF EXISTS validations_validator_id_fkey;
ALTER TABLE stories DROP CONSTRAINT IF EXISTS stories_user_id_fkey;
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_user_id_fkey;
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_referred_by_id_fkey;
ALTER TABLE user_interests DROP CONSTRAINT IF EXISTS user_interests_user_id_fkey;
ALTER TABLE referral_stats DROP CONSTRAINT IF EXISTS referral_stats_ambassador_id_fkey;
ALTER TABLE transactions DROP CONSTRAINT IF EXISTS transactions_user_id_fkey;
ALTER TABLE video_clips DROP CONSTRAINT IF EXISTS video_clips_user_id_fkey;
ALTER TABLE notification_logs DROP CONSTRAINT IF EXISTS notification_logs_user_id_fkey;
ALTER TABLE clip_flags DROP CONSTRAINT IF EXISTS clip_flags_flagged_by_fkey;
ALTER TABLE clip_flags DROP CONSTRAINT IF EXISTS clip_flags_resolved_by_fkey;
ALTER TABLE withdrawals DROP CONSTRAINT IF EXISTS withdrawals_user_id_fkey;
ALTER TABLE payout_requests DROP CONSTRAINT IF EXISTS payout_requests_user_id_fkey;
ALTER TABLE reports DROP CONSTRAINT IF EXISTS reports_reporter_id_fkey;
ALTER TABLE reports DROP CONSTRAINT IF EXISTS reports_reported_user_id_fkey;
ALTER TABLE reports DROP CONSTRAINT IF EXISTS reports_resolver_id_fkey;
ALTER TABLE conversations DROP CONSTRAINT IF EXISTS conversations_created_by_fkey;
ALTER TABLE live_messages DROP CONSTRAINT IF EXISTS live_messages_user_id_fkey;
ALTER TABLE conversation_members DROP CONSTRAINT IF EXISTS conversation_members_user_id_fkey;
ALTER TABLE messages DROP CONSTRAINT IF EXISTS messages_sender_id_fkey;
ALTER TABLE daily_prompts DROP CONSTRAINT IF EXISTS daily_prompts_user_id_fkey;
ALTER TABLE user_devices DROP CONSTRAINT IF EXISTS user_devices_user_id_fkey;
ALTER TABLE story_views DROP CONSTRAINT IF EXISTS story_views_user_id_fkey;
ALTER TABLE referrals DROP CONSTRAINT IF EXISTS referrals_referred_user_id_fkey;
ALTER TABLE referral_codes DROP CONSTRAINT IF EXISTS referral_codes_owner_user_id_fkey;
ALTER TABLE live_streams DROP CONSTRAINT IF EXISTS live_streams_streamer_id_fkey;

-- 2. Add constraints back with ON UPDATE CASCADE
ALTER TABLE voice_clips ADD CONSTRAINT voice_clips_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE likes ADD CONSTRAINT likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE comments ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE followers ADD CONSTRAINT followers_follower_id_fkey FOREIGN KEY (follower_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE followers ADD CONSTRAINT followers_following_id_fkey FOREIGN KEY (following_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE user_badges ADD CONSTRAINT user_badges_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE validations ADD CONSTRAINT validations_validator_id_fkey FOREIGN KEY (validator_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE stories ADD CONSTRAINT stories_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE profiles ADD CONSTRAINT profiles_referred_by_id_fkey FOREIGN KEY (referred_by) REFERENCES profiles(id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE user_interests ADD CONSTRAINT user_interests_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE referral_stats ADD CONSTRAINT referral_stats_ambassador_id_fkey FOREIGN KEY (ambassador_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE transactions ADD CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE video_clips ADD CONSTRAINT video_clips_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE notification_logs ADD CONSTRAINT notification_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE clip_flags ADD CONSTRAINT clip_flags_flagged_by_fkey FOREIGN KEY (flagged_by) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE clip_flags ADD CONSTRAINT clip_flags_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES profiles(id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE withdrawals ADD CONSTRAINT withdrawals_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE payout_requests ADD CONSTRAINT payout_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE reports ADD CONSTRAINT reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE reports ADD CONSTRAINT reports_reported_user_id_fkey FOREIGN KEY (reported_user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE reports ADD CONSTRAINT reports_resolver_id_fkey FOREIGN KEY (resolver_id) REFERENCES profiles(id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE conversations ADD CONSTRAINT conversations_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE live_messages ADD CONSTRAINT live_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE conversation_members ADD CONSTRAINT conversation_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE messages ADD CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE daily_prompts ADD CONSTRAINT daily_prompts_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE user_devices ADD CONSTRAINT user_devices_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE story_views ADD CONSTRAINT story_views_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE referrals ADD CONSTRAINT referrals_referred_user_id_fkey FOREIGN KEY (referred_user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE referral_codes ADD CONSTRAINT referral_codes_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE live_streams ADD CONSTRAINT live_streams_streamer_id_fkey FOREIGN KEY (streamer_id) REFERENCES profiles(id) ON DELETE CASCADE ON UPDATE CASCADE;
